// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Adquisicion
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Nueva Adquicision - Pago Contado")]
    [NUnit.Framework.CategoryAttribute("NuevaAdquisicion")]
    public partial class NuevaAdquicision_PagoContadoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "NuevaAdquisicion"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Adquisicion", "Nueva Adquicision - Pago Contado", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NewAdquisicionContado.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro exitoso con Pago Contado Efectivo")]
        [NUnit.Framework.CategoryAttribute("RegistroAdquisicionPagoContado")]
        public async System.Threading.Tasks.Task RegistroExitosoConPagoContadoEfectivo()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroAdquisicionPagoContado"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso con Pago Contado Efectivo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table1.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table1.AddRow(new string[] {
                            "Serie",
                            "B200"});
                table1.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table1.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table1.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table1.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 9
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table1, "When ");
#line hidden
#line 18
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table2.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table2.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table2.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 19
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table2, "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table3.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 25
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table3, "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table4.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table4.AddRow(new string[] {
                            "Método",
                            "Efectivo"});
                table4.AddRow(new string[] {
                            "Observación",
                            "NINGUNO"});
#line 29
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table4, "And ");
#line hidden
#line 35
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro Adquisicion Pago Contado Billetera Digital")]
        public async System.Threading.Tasks.Task RegistroAdquisicionPagoContadoBilleteraDigital()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro Adquisicion Pago Contado Billetera Digital", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table5.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table5.AddRow(new string[] {
                            "Serie",
                            "B201"});
                table5.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table5.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table5.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table5.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 43
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table5, "When ");
#line hidden
#line 52
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table6.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table6.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table6.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 53
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table6, "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table7.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 59
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table7, "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table8.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table8.AddRow(new string[] {
                            "Método",
                            "Billetera digital"});
                table8.AddRow(new string[] {
                            "Billetera",
                            "Yape"});
                table8.AddRow(new string[] {
                            "Código",
                            "123456789"});
                table8.AddRow(new string[] {
                            "Observación",
                            "NINGUNO"});
#line 63
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table8, "And ");
#line hidden
#line 71
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro Adquisicion Pago Contado Tarjeta de Credito")]
        public async System.Threading.Tasks.Task RegistroAdquisicionPagoContadoTarjetaDeCredito()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro Adquisicion Pago Contado Tarjeta de Credito", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table9.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table9.AddRow(new string[] {
                            "Serie",
                            "B202"});
                table9.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table9.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table9.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table9.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 79
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table9, "When ");
#line hidden
#line 88
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table10.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table10.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table10.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 89
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table10, "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table11.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 95
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table11, "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table12.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table12.AddRow(new string[] {
                            "Método",
                            "Tarjeta de credito"});
                table12.AddRow(new string[] {
                            "Tarjeta",
                            "VISA"});
                table12.AddRow(new string[] {
                            "Información",
                            "NINGUNO"});
#line 99
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table12, "And ");
#line hidden
#line 106
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro Adquisicion Pago Contado Tarjeta de Debito")]
        public async System.Threading.Tasks.Task RegistroAdquisicionPagoContadoTarjetaDeDebito()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro Adquisicion Pago Contado Tarjeta de Debito", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 110
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table13.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table13.AddRow(new string[] {
                            "Serie",
                            "B203"});
                table13.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table13.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table13.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table13.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 114
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table13, "When ");
#line hidden
#line 123
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table14.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table14.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table14.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 124
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table15.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 130
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table15, "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table16.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table16.AddRow(new string[] {
                            "Método",
                            "Tarjeta de DǸbito"});
                table16.AddRow(new string[] {
                            "Tarjeta",
                            "DINERS CLUB"});
                table16.AddRow(new string[] {
                            "Información",
                            "NINGUNO"});
#line 134
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table16, "And ");
#line hidden
#line 141
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 142
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro Adquisicion Pago Contado Transferencia en Cuenta")]
        public async System.Threading.Tasks.Task RegistroAdquisicionPagoContadoTransferenciaEnCuenta()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro Adquisicion Pago Contado Transferencia en Cuenta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 145
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 146
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table17.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table17.AddRow(new string[] {
                            "Serie",
                            "B204"});
                table17.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table17.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table17.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table17.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 149
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table17, "When ");
#line hidden
#line 158
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table18.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table18.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table18.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 159
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table18, "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table19.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 165
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table19, "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table20.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table20.AddRow(new string[] {
                            "Método",
                            "Transferecia en Cuenta"});
                table20.AddRow(new string[] {
                            "Cuenta Bancaria Propia",
                            "TSOL123456789"});
                table20.AddRow(new string[] {
                            "Cuenta bancaria del proveedor",
                            "1110987654321"});
                table20.AddRow(new string[] {
                            "Información",
                            "NINGUNO"});
#line 169
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table20, "And ");
#line hidden
#line 177
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 178
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro Adquisicion Pago Contado Deposito en Cuenta")]
        public async System.Threading.Tasks.Task RegistroAdquisicionPagoContadoDepositoEnCuenta()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro Adquisicion Pago Contado Deposito en Cuenta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 180
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 181
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 182
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 183
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table21.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table21.AddRow(new string[] {
                            "Serie",
                            "B205"});
                table21.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table21.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table21.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table21.AddRow(new string[] {
                            "Información Adicional",
                            "Boleta Exitosa"});
#line 185
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table21, "When ");
#line hidden
#line 194
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table22.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table22.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table22.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 195
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table23.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "150",
                            "6.9"});
#line 201
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table23, "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table24.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table24.AddRow(new string[] {
                            "Método",
                            "Deposito en Cuenta"});
                table24.AddRow(new string[] {
                            "Caja",
                            "TSOL123456789"});
                table24.AddRow(new string[] {
                            "Número de cuenta bancaria del proveedor",
                            "1110987654321"});
                table24.AddRow(new string[] {
                            "Información",
                            "NINGUNO"});
#line 205
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table24, "And ");
#line hidden
#line 213
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 214
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
