// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Adquisicion
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NuevaAdquisicionNewConcepto")]
    [NUnit.Framework.CategoryAttribute("NuevaAdquisicionB_ConNuevoConcepto")]
    public partial class NuevaAdquisicionNewConceptoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "NuevaAdquisicionB_ConNuevoConcepto"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Adquisicion", "NuevaAdquisicionNewConcepto", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevaAdquisicionNewConcepto.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Regsitro exitoso de Nueva Adquisicion con Nuevo Concepto")]
        public async System.Threading.Tasks.Task RegsitroExitosoDeNuevaAdquisicionConNuevoConcepto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Regsitro exitoso de Nueva Adquisicion con Nuevo Concepto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table105 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table105.AddRow(new string[] {
                            "Documento",
                            "BOLETA DE VENTA ELECTRONICA"});
                table105.AddRow(new string[] {
                            "Serie",
                            "B001"});
                table105.AddRow(new string[] {
                            "Correlativo",
                            "00000010"});
                table105.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table105.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table105.AddRow(new string[] {
                            "Información Adicional",
                            "Compra con concepto nuevo"});
#line 9
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table105, "When ");
#line hidden
#line 18
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table106 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table106.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table106.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table106.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 19
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table106, "And ");
#line hidden
#line 25
 await testRunner.AndAsync("Se abre el modal de \'Nuevo Concepto\' en la sección de productos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table107 = new global::Reqnroll.Table(new string[] {
                            "familia",
                            "codigo",
                            "sufijo",
                            "marca",
                            "presentacion",
                            "tarifa",
                            "precio"});
                table107.AddRow(new string[] {
                            "HISOPO",
                            "INS0111",
                            "PARA USO MEDICO",
                            "TextilPeru",
                            "SP",
                            "POR UNIDAD",
                            "10"});
#line 26
 await testRunner.AndAsync("Se registran los datos del nuevo concepto en el modal:", ((string)(null)), table107, "And ");
#line hidden
#line 31
 await testRunner.AndAsync("Se guarda el concepto desde el modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table108 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table108.AddRow(new string[] {
                            "INS0111",
                            "100",
                            "6.9"});
#line 33
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table108, "And ");
#line hidden
                global::Reqnroll.Table table109 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table109.AddRow(new string[] {
                            "Tipo",
                            "Contado"});
                table109.AddRow(new string[] {
                            "Método",
                            "Efectivo"});
                table109.AddRow(new string[] {
                            "Observación",
                            "NINGUNO"});
#line 37
 await testRunner.AndAsync("Se configuran los datos de \'Pago\':", ((string)(null)), table109, "And ");
#line hidden
#line 43
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
