// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Adquisicion
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Nueva Adquicision - Tipo de Entrega Imnmediata")]
    [NUnit.Framework.CategoryAttribute("NuevaAdquisicion")]
    public partial class NuevaAdquicision_TipoDeEntregaImnmediataFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "NuevaAdquisicion"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Adquisicion", "Nueva Adquicision - Tipo de Entrega Imnmediata", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevaAdquisicionEntregaInmediata.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro exitoso con Entrega Imnmediata")]
        [NUnit.Framework.CategoryAttribute("RegistroAdquisicionExitosa-EntregaInmediata")]
        public async System.Threading.Tasks.Task RegistroExitosoConEntregaImnmediata()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroAdquisicionExitosa-EntregaInmediata"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso con Entrega Imnmediata", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table41.AddRow(new string[] {
                            "Documento",
                            "FACTURA ELECTRONICA"});
                table41.AddRow(new string[] {
                            "Serie",
                            "F005"});
                table41.AddRow(new string[] {
                            "Correlativo",
                            "00000014"});
                table41.AddRow(new string[] {
                            "Fecha de emisión",
                            "04/03/2026"});
                table41.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table41.AddRow(new string[] {
                            "Información Adicional",
                            "Factura Exitosa"});
#line 10
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table41, "When ");
#line hidden
#line 19
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Imnmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table42.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table42.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table42.AddRow(new string[] {
                            "Almacén",
                            "ALMACEN CENTRAL"});
#line 20
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table42, "And ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table43.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "16",
                            "6.59"});
#line 26
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table43, "And ");
#line hidden
#line 30
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro exitoso con Entrega Inmediata con Varios Almacenes")]
        public async System.Threading.Tasks.Task RegistroExitosoConEntregaInmediataConVariosAlmacenes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso con Entrega Inmediata con Varios Almacenes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table44.AddRow(new string[] {
                            "Documento",
                            "FACTURA ELECTRONICA"});
                table44.AddRow(new string[] {
                            "Serie",
                            "F004"});
                table44.AddRow(new string[] {
                            "Correlativo",
                            "00000013"});
                table44.AddRow(new string[] {
                            "Fecha de emisión",
                            "09/03/2026"});
                table44.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table44.AddRow(new string[] {
                            "Información Adicional",
                            "Prueba Varios Inme"});
#line 38
    await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table44, "When ");
#line hidden
#line 48
    await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("Se activa la opción de \'Varios\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Rol",
                            "Almacén",
                            "Cantidad",
                            "V. U"});
                table45.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "Item Comercial",
                            "CENTRO COMERCIAL CENTRAL",
                            "19",
                            "6.9"});
                table45.AddRow(new string[] {
                            "7751234001122|Azúcar Blanca",
                            "Item Comercial",
                            "ALMACEN CENTRAL",
                            "17",
                            "6.7"});
#line 51
    await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table45, "And ");
#line hidden
#line 56
    await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
    await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
