// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Adquisicion
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Nueva Adquicision - Tipo de Documento NotaInterna")]
    [NUnit.Framework.CategoryAttribute("NuevaAdquisicionB")]
    public partial class NuevaAdquicision_TipoDeDocumentoNotaInternaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "NuevaAdquisicionB"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Adquisicion", "Nueva Adquicision - Tipo de Documento NotaInterna", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevaAdquisicionNota.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro exitoso con Nota Interna")]
        [NUnit.Framework.CategoryAttribute("RegistroAdquisicionExitosa-Nota")]
        public async System.Threading.Tasks.Task RegistroExitosoConNotaInterna()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroAdquisicionExitosa-Nota"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso con Nota Interna", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync("Inicio de sesión en el módulo de Adquisición con usuario \'pamela.tone@recsa.com\' " +
                        "y contraseña \'calidad\' en \'https://sigesdev.newfrontdev-qa.sigesonline.com/auth/" +
                        "login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.AndAsync("Navego al módulo de \'Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
 await testRunner.AndAsync("Entro al submódulo específico de \'Nueva Adquisición\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table105 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table105.AddRow(new string[] {
                            "Documento",
                            "NOTA DE COMPRA (INTERNA)"});
                table105.AddRow(new string[] {
                            "Proveedor",
                            "10759012017"});
                table105.AddRow(new string[] {
                            "Información Adicional",
                            "Nota Exitosa"});
#line 9
 await testRunner.WhenAsync("Se configuran los datos de \'Facturación\':", ((string)(null)), table105, "When ");
#line hidden
#line 15
 await testRunner.AndAsync("Se selecciona el tipo de entrega \'Inmediata\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table106 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table106.AddRow(new string[] {
                            "Rol",
                            "Item Comercial"});
                table106.AddRow(new string[] {
                            "Establecimiento",
                            "RECSA - CENTRAL"});
                table106.AddRow(new string[] {
                            "Almacén",
                            "CENTRO COMERCIAL CENTRAL"});
#line 16
 await testRunner.AndAsync("Se configuran los datos de \'Entrega\':", ((string)(null)), table106, "And ");
#line hidden
                global::Reqnroll.Table table107 = new global::Reqnroll.Table(new string[] {
                            "Producto",
                            "Cantidad",
                            "V. U"});
                table107.AddRow(new string[] {
                            "7751234001115|Azúcar Rubia",
                            "1500",
                            "6.9"});
#line 22
 await testRunner.AndAsync("Se selecciona y configura el producto a adquirir:", ((string)(null)), table107, "And ");
#line hidden
#line 26
 await testRunner.ThenAsync("Se procede a guardar la adquisición mediante la acción \'SavePurchase\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
 await testRunner.AndAsync("Se confirma el registro exitoso con el mensaje \'Se registró correctamente.\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
