// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Items.ChecklistAndPartEquivalenceAnalyBoundary_Items.TestE2E
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TestE2EFeature")]
    public partial class TestE2EFeatureFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Items/Checklist and PartEquivalence AnalyBoundary-Items/TestE2E", "TestE2EFeature", "Se realizará una prueba end-to-end para validar la correcta integración entre los" +
                "\r\nsubmódulos del módulo Conceptos y garantizar el flujo funcional completo del s" +
                "istema.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "TestE2EFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
await testRunner.GivenAsync("el usuario ingresa al ambiente \'https://sigesdev.newfrontdev-qa.sigesonline.com/a" +
                    "uth/login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
await testRunner.WhenAsync("el usuario inicia sesión con usuario \'pamela.tone@recsa.com\' y contraseña \'calida" +
                    "d\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.AndAsync("el usuario accede al módulo Conceptos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar un concepto mediante un flujo end-to-end completo")]
        public async System.Threading.Tasks.Task RegistrarUnConceptoMedianteUnFlujoEnd_To_EndCompleto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar un concepto mediante un flujo end-to-end completo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 13
await testRunner.WhenAsync("el usuario selecciona Registrar Datos de Concepto", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
await testRunner.AndAsync("el usuario selecciona la opción Características", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
await testRunner.AndAsync("el usuario selecciona el tipo de Caracteristica \"Comun\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
await testRunner.AndAsync("el usuario ingresa el nombre de Caracteristica Comun \"TIPO DE SOPORTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
await testRunner.ThenAsync("se guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
await testRunner.WhenAsync("el usuario selecciona el tipo de Caracteristica \"Propia\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.AndAsync("el usuario ingresa el codigo de caracteristica propia \"QA001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
await testRunner.AndAsync("el usuario ingresa el nombre de caracteristica propia \"TIEMPO DE ATENCION\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
await testRunner.AndAsync("el usuario selecciona el tipo de dato \"Texto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
await testRunner.ThenAsync("se guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
await testRunner.WhenAsync("el usuario selecciona la opcion Valor de Caracteristica", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.AndAsync("el usuario selecciona la caracteristica comun \"TIPO DE SOPORTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
await testRunner.AndAsync("el usuario ingresa el valor de caracteristica comun \"REMOTO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
await testRunner.AndAsync("el usuario guarda el valor de caracteristica comun", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
await testRunner.ThenAsync("el sistema muestra un mensaje de confirmacion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
await testRunner.WhenAsync("el usuario ingresa el valor de caracteristica comun \"PRESENCIAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
await testRunner.AndAsync("el usuario guarda el valor de caracteristica comun", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
await testRunner.ThenAsync("el sistema muestra un mensaje de confirmacion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
await testRunner.WhenAsync("el usuario ingresa el valor de caracteristica comun \"EMPRESARIAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
await testRunner.AndAsync("el usuario guarda el valor de caracteristica comun", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
await testRunner.ThenAsync("el sistema muestra un mensaje de confirmacion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
await testRunner.WhenAsync("el usuario selecciona la opcion Presentación", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
await testRunner.AndAsync("el usuario ingresa el codigo de presentación \"PRES-QA\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
await testRunner.AndAsync("el usuario ingresa el nombre de presentación \"SOPORTE DIGITAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
await testRunner.AndAsync("el usuario ingresa la descripcion de presentación \"No hay presentacion\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
await testRunner.ThenAsync("se guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
await testRunner.WhenAsync("el usuario selecciona la opción Categoría", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
await testRunner.AndAsync("el usuario ingresa el nombre de categoría \"SOPORTE TECNOLÓGICO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
await testRunner.AndAsync("el usuario ingresa la descripcion de categoría \"Soporte Tecnológico a Empresas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
await testRunner.ThenAsync("se guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
await testRunner.WhenAsync("el usuario selecciona la opción Familia", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.AndAsync("el usuario selecciona el tipo \"Bien\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
await testRunner.AndAsync("el usuario selecciona el tipo de tratamiento \"IGV Restaurantes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
await testRunner.AndAsync("el usuario ingresa el código de familia \"FAM-QA\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
await testRunner.AndAsync("el usuario ingresa el nombre de familia \"SERVICIOS DE SOPORTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
await testRunner.AndAsync("el usuario selecciona la categoria \"SOPORTE TECNOLÓGICO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
await testRunner.AndAsync("el usuario ingresa la caracteristica comun \"TIPO DE SOPORTE\" y su estado \"Activo\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
await testRunner.ThenAsync("se guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
await testRunner.WhenAsync("el usuario selecciona la opcion Asignar Valor de Caracteristica", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
await testRunner.AndAsync("el usuario selecciona la Familia a asignar \"SERVICIOS DE SOPORTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
await testRunner.AndAsync("el usuario arrastra el valor \"REMOTO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
await testRunner.ThenAsync("se guarda la asignacion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
await testRunner.WhenAsync("el usuario selecciona Nuevo Concepto", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
await testRunner.AndAsync("el usuario selecciona la Familia \"SERVICIOS DE SOPORTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
await testRunner.AndAsync("el usuario selecciona Auto al Código", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
await testRunner.AndAsync("el usuario ingresa el Sufijo \"loco\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
await testRunner.AndAsync("el usuario selecciona el Rol \"Item Comercial\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
await testRunner.AndAsync("el usuario selecciona el Módulo a Mostrar \"MOD0001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
await testRunner.AndAsync("el usuario selecciona la Marca \"REMOTO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
await testRunner.AndAsync("el usuario selecciona la Presentación \"SOPORTE DIGITAL\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
await testRunner.AndAsync("el usuario ingresa la Cantidad \"30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
await testRunner.AndAsync("el usuario selecciona la tarifa \"POR UNIDAD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
await testRunner.AndAsync("el usuario ingresa el Precio \"100\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
await testRunner.ThenAsync("Guardar concepto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
