// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FLOTA_VEHICULAR.Features.Mantenimiento
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Gestión del Catálogo de Mantenimiento")]
    [NUnit.Framework.CategoryAttribute("ModuloMantenimiento")]
    public partial class GestionDelCatalogoDeMantenimientoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "ModuloMantenimiento"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Mantenimiento", "Gestión del Catálogo de Mantenimiento", "  Como administrador del sistema\r\n  Quiero acceder y gestionar el catálogo de man" +
                "tenimiento\r\n  Para mantener actualizados los servicios vehiculares", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "VerCatalogo.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ingresar exitosamente al submódulo Ver Catálogos")]
        [NUnit.Framework.CategoryAttribute("NavegacionCatalogo_CP001")]
        public async System.Threading.Tasks.Task IngresarExitosamenteAlSubmoduloVerCatalogos()
        {
            string[] tagsOfScenario = new string[] {
                    "NavegacionCatalogo_CP001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingresar exitosamente al submódulo Ver Catálogos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro exitoso de un nuevo catálogo de mantenimiento")]
        [NUnit.Framework.CategoryAttribute("RegistroCatalogo_CP002")]
        public async System.Threading.Tasks.Task RegistroExitosoDeUnNuevoCatalogoDeMantenimiento()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroCatalogo_CP002"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro exitoso de un nuevo catálogo de mantenimiento", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table1.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table1.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table1.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table1.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "02/04/2026"});
                table1.AddRow(new string[] {
                            "FECHA FIN",
                            "02/04/2027"});
                table1.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 27
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table1, "And ");
#line hidden
#line 36
  await testRunner.ThenAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar catalogo con fechas solapadas con catálogo en estado ACTIVO existente.")]
        [NUnit.Framework.CategoryAttribute("BloqueoCatalogoSolapado_CP028")]
        public async System.Threading.Tasks.Task RegistrarCatalogoConFechasSolapadasConCatalogoEnEstadoACTIVOExistente_()
        {
            string[] tagsOfScenario = new string[] {
                    "BloqueoCatalogoSolapado_CP028"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar catalogo con fechas solapadas con catálogo en estado ACTIVO existente.", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table2.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table2.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table2.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table2.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "01/01/2050"});
                table2.AddRow(new string[] {
                            "FECHA FIN",
                            "31/12/2050"});
                table2.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 50
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table2, "And ");
#line hidden
#line 59
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table3.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table3.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table3.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table3.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "15/01/2026"});
                table3.AddRow(new string[] {
                            "FECHA FIN",
                            "15/01/2027"});
                table3.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 67
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table3, "And ");
#line hidden
#line 75
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
  await testRunner.ThenAsync("el sistema debe impedir el registro y mostrar un error de fechas solapadas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de catálogo con catálogo anterior en estado ACTIVO pero sin fechas SOLAP" +
            "ADAS")]
        [NUnit.Framework.CategoryAttribute("RegistroCatalogoSinSolapar_CP029")]
        public async System.Threading.Tasks.Task RegistroDeCatalogoConCatalogoAnteriorEnEstadoACTIVOPeroSinFechasSOLAPADAS()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroCatalogoSinSolapar_CP029"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de catálogo con catálogo anterior en estado ACTIVO pero sin fechas SOLAP" +
                    "ADAS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table4.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table4.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "C"});
                table4.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table4.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "01/01/2029"});
                table4.AddRow(new string[] {
                            "FECHA FIN",
                            "02/01/2029"});
                table4.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 93
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table4, "And ");
#line hidden
#line 101
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table5.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table5.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "C"});
                table5.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table5.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "03/02/2029"});
                table5.AddRow(new string[] {
                            "FECHA FIN",
                            "04/02/2029"});
                table5.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 108
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table5, "And ");
#line hidden
#line 119
  await testRunner.ThenAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 120
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar catálogo con fechas solapadas pero con catlaogo anterior en estado DE B" +
            "AJA")]
        [NUnit.Framework.CategoryAttribute("RegistroCatalogoSolapadoConBaja_CP030")]
        public async System.Threading.Tasks.Task RegistrarCatalogoConFechasSolapadasPeroConCatlaogoAnteriorEnEstadoDEBAJA()
        {
            string[] tagsOfScenario = new string[] {
                    "RegistroCatalogoSolapadoConBaja_CP030"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar catálogo con fechas solapadas pero con catlaogo anterior en estado DE B" +
                    "AJA", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 125
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 129
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 130
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table6.AddRow(new string[] {
                            "CLASIFICADOR",
                            "MEDIA"});
                table6.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table6.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "BI-COMBUSTIBLE"});
                table6.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "05/02/2040"});
                table6.AddRow(new string[] {
                            "FECHA FIN",
                            "07/02/2040"});
                table6.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 134
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table6, "And ");
#line hidden
#line 142
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
 await testRunner.WhenAsync("Se busca por fechas \"05/02/2040\" y \"07/02/2040\" y se da de baja el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table7.AddRow(new string[] {
                            "CLASIFICADOR",
                            "MEDIA"});
                table7.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table7.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "BI-COMBUSTIBLE"});
                table7.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "05/02/2040"});
                table7.AddRow(new string[] {
                            "FECHA FIN",
                            "07/02/2040"});
                table7.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 157
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table7, "And ");
#line hidden
#line 165
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registrar catálogo con campos obligatorios vacíos (general)")]
        [NUnit.Framework.CategoryAttribute("CamposVacios_CP026")]
        public async System.Threading.Tasks.Task RegistrarCatalogoConCamposObligatoriosVaciosGeneral()
        {
            string[] tagsOfScenario = new string[] {
                    "CamposVacios_CP026"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar catálogo con campos obligatorios vacíos (general)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 170
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 171
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 172
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 182
  await testRunner.ThenAsync("el botón Guardar debe estar deshabilitado para impedir el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editar catálogo con estado VIGENTE (CP037)(cp033)")]
        [NUnit.Framework.CategoryAttribute("EdicionCatalogoVigente_CP037")]
        public async System.Threading.Tasks.Task EditarCatalogoConEstadoVIGENTECP037Cp033()
        {
            string[] tagsOfScenario = new string[] {
                    "EdicionCatalogoVigente_CP037"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar catálogo con estado VIGENTE (CP037)(cp033)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 185
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 189
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 190
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 191
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 193
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table8.AddRow(new string[] {
                            "CLASIFICADOR",
                            "MEDIA"});
                table8.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table8.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table8.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "02/01/2042"});
                table8.AddRow(new string[] {
                            "FECHA FIN",
                            "03/01/2042"});
                table8.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 194
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table8, "And ");
#line hidden
#line 202
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 208
  await testRunner.WhenAsync("Se busca por fechas \"02/01/2042\" y \"03/01/2042\" y se abre el detalle", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 214
  await testRunner.WhenAsync("Se edita el catálogo agregando la actividad \"LIMPIEZA DE BUJÍAS\" y eliminando la " +
                        "fila 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 215
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editar fecha de catálogo CADUCADO para que cambie a VIGENTE (CP039-cp035)")]
        [NUnit.Framework.CategoryAttribute("EdicionCaducadoAVigente_CP039")]
        public async System.Threading.Tasks.Task EditarFechaDeCatalogoCADUCADOParaQueCambieAVIGENTECP039_Cp035()
        {
            string[] tagsOfScenario = new string[] {
                    "EdicionCaducadoAVigente_CP039"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar fecha de catálogo CADUCADO para que cambie a VIGENTE (CP039-cp035)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 223
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 224
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 225
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 226
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
  await testRunner.WhenAsync("Se busca el primer catálogo en estado \"CADUCADO\" y se edita", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 233
  await testRunner.AndAsync("Se actualizan las fechas del catálogo a inicio \"01/01/2026\" y fin \"31/12/2026\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 238
  await testRunner.AndAsync("el estado del catálogo editado debe cambiar a \"VIGENTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editar catálogo CADUCADO con fecha pasada (CP038)(cp034)")]
        [NUnit.Framework.CategoryAttribute("EdicionCaducadoFechaPasada_CP038")]
        public async System.Threading.Tasks.Task EditarCatalogoCADUCADOConFechaPasadaCP038Cp034()
        {
            string[] tagsOfScenario = new string[] {
                    "EdicionCaducadoFechaPasada_CP038"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar catálogo CADUCADO con fecha pasada (CP038)(cp034)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 244
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 245
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 246
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 247
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 250
  await testRunner.WhenAsync("Se busca el primer catálogo en estado \"CADUCADO\" y se edita", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 253
  await testRunner.AndAsync("Se actualizan las fechas del catálogo a inicio \"01/01/2022\" y fin \"31/12/2022\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 256
  await testRunner.ThenAsync("el sistema debe impedir asignar una fecha pasada bloqueando el botón guardar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clonar catálogo con nueva Fecha de Inicio menor a la del origen (CP031)(cp027)")]
        [NUnit.Framework.CategoryAttribute("ClonarCatalogoFechaMenor_CP031")]
        public async System.Threading.Tasks.Task ClonarCatalogoConNuevaFechaDeInicioMenorALaDelOrigenCP031Cp027()
        {
            string[] tagsOfScenario = new string[] {
                    "ClonarCatalogoFechaMenor_CP031"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clonar catálogo con nueva Fecha de Inicio menor a la del origen (CP031)(cp027)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 263
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 264
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 265
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 266
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table9.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table9.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table9.AddRow(new string[] {
                            "TIPO DE MOTOR",
                            "COMBUSTIBLE"});
                table9.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "15/02/2043"});
                table9.AddRow(new string[] {
                            "FECHA FIN",
                            "31/12/2043"});
                table9.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 268
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table9, "And ");
#line hidden
#line 276
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 277
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 282
  await testRunner.WhenAsync("Se busca por fechas \"15/02/2026\" y \"31/12/2026\" y se abre el detalle", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 283
  await testRunner.AndAsync("Se hace clic en el botón Clonar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table10.AddRow(new string[] {
                            "CLASIFICADOR",
                            "ALTA"});
                table10.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table10.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "10/02/2043"});
                table10.AddRow(new string[] {
                            "FECHA FIN",
                            "31/12/2043"});
#line 289
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table10, "And ");
#line hidden
#line 295
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 300
  await testRunner.ThenAsync("el sistema debe mostrar un error de solapamiento de fechas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clonar un catálogo origen que está en estado DEBAJA(cp28).")]
        [NUnit.Framework.CategoryAttribute("ClonarDeBaja_Ideal_CP032")]
        public async System.Threading.Tasks.Task ClonarUnCatalogoOrigenQueEstaEnEstadoDEBAJACp28_()
        {
            string[] tagsOfScenario = new string[] {
                    "ClonarDeBaja_Ideal_CP032"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clonar un catálogo origen que está en estado DEBAJA(cp28).", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 305
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 306
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 307
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 308
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 311
  await testRunner.WhenAsync("Se hace clic en el botón Nuevo Catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table11.AddRow(new string[] {
                            "CLASIFICADOR",
                            "MEDIA"});
                table11.AddRow(new string[] {
                            "CLASE DE MANTENIMIENTO",
                            "A"});
                table11.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "01/01/2047"});
                table11.AddRow(new string[] {
                            "FECHA FIN",
                            "31/12/2047"});
                table11.AddRow(new string[] {
                            "ACTIVIDADES",
                            "Limpieza y regulación de frenos"});
#line 312
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table11, "And ");
#line hidden
#line 319
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 322
  await testRunner.WhenAsync("Se busca por fechas \"01/01/2047\" y \"31/12/2047\" y se da de baja el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 325
  await testRunner.WhenAsync("Se busca por fechas \"01/01/2028\" y \"31/12/2028\" y se abre el detalle", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 326
  await testRunner.AndAsync("Se hace clic en el botón Clonar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table12.AddRow(new string[] {
                            "FECHA DE INICIO",
                            "01/01/2047"});
                table12.AddRow(new string[] {
                            "FECHA FIN",
                            "31/12/2047"});
#line 327
  await testRunner.AndAsync("Se ingresan los datos del nuevo catálogo:", ((string)(null)), table12, "And ");
#line hidden
#line 331
  await testRunner.AndAsync("Se modifica la lista de actividades agregando \"LIMPIEZA DE BUJÍAS\" y eliminando l" +
                        "a fila 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("v2 Clonar un catálogo origen que ya está en estado DE BAJA (CP032)")]
        [NUnit.Framework.CategoryAttribute("ClonarDeBaja_Workaround_CP032")]
        public async System.Threading.Tasks.Task V2ClonarUnCatalogoOrigenQueYaEstaEnEstadoDEBAJACP032()
        {
            string[] tagsOfScenario = new string[] {
                    "ClonarDeBaja_Workaround_CP032"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("v2 Clonar un catálogo origen que ya está en estado DE BAJA (CP032)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 338
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 339
  await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 340
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 341
  await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 344
  await testRunner.WhenAsync("Se busca el primer catálogo en estado \"DE BAJA\" y se clona", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 347
  await testRunner.AndAsync("Se modifica la lista de actividades agregando \"LIMPIEZA DE BUJÍAS\" y eliminando l" +
                        "a fila 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 349
  await testRunner.AndAsync("Se procede a Guardar el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 352
  await testRunner.ThenAsync("el catálogo debe guardarse exitosamente sin errores de solapamiento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Clonar catálogo dejando campos obligatorios vacíos")]
        [NUnit.Framework.CategoryAttribute("ClonarCamposVacios_CP031")]
        public async System.Threading.Tasks.Task ClonarCatalogoDejandoCamposObligatoriosVacios()
        {
            string[] tagsOfScenario = new string[] {
                    "ClonarCamposVacios_CP031"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clonar catálogo dejando campos obligatorios vacíos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 357
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 358
    await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 359
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 360
    await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 363
    await testRunner.WhenAsync("Se busca el primer catálogo en estado \"VIGENTE\" y se clona", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 366
    await testRunner.AndAsync("Se eliminan todas las actividades precargadas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 369
    await testRunner.ThenAsync("el botón Guardar debe estar deshabilitado para impedir el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Listar catálogo por estado VIGENTE (CP074)")]
        [NUnit.Framework.CategoryAttribute("FiltroEstadoVigente_CP074")]
        public async System.Threading.Tasks.Task ListarCatalogoPorEstadoVIGENTECP074()
        {
            string[] tagsOfScenario = new string[] {
                    "FiltroEstadoVigente_CP074"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar catálogo por estado VIGENTE (CP074)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 373
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 374
    await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 375
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 376
    await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 379
    await testRunner.WhenAsync("Se limpian los filtros y se selecciona el estado \"VIGENTE\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 380
    await testRunner.AndAsync("Se hace clic en el botón BUSCAR principal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 383
    await testRunner.ThenAsync("todos los resultados en la columna \"ESTADO-CATALOGO\" deben coincidir con \"VIGENTE" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Listar catálogo por estado CADUCADO (CP075)")]
        [NUnit.Framework.CategoryAttribute("FiltroEstadoCaducado_CP075")]
        public async System.Threading.Tasks.Task ListarCatalogoPorEstadoCADUCADOCP075()
        {
            string[] tagsOfScenario = new string[] {
                    "FiltroEstadoCaducado_CP075"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar catálogo por estado CADUCADO (CP075)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 387
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 388
    await testRunner.GivenAsync("el usuario ingresa al ambiente \"https://sigesoas.mimp-qa.sigesonline.com/#/public" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 389
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \"ADMIN-GLOBAL\" y contraseña \"Admin2023Global" +
                        "*\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 390
    await testRunner.AndAsync("Se ingresa al módulo Mantenimiento y submódulo Ver Catálogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 393
    await testRunner.WhenAsync("Se limpian los filtros y se selecciona el estado \"CADUCADO\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 394
    await testRunner.AndAsync("Se hace clic en el botón BUSCAR principal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
    await testRunner.ThenAsync("todos los resultados en la columna \"ESTADO-CATALOGO\" deben coincidir con \"CADUCAD" +
                        "O\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
