// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.SharedVentas
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CreacionCliente")]
    public partial class CreacionClienteFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/SharedVentas", "CreacionCliente", "CP001: Creación de cliente con DNI - Persona Natural con búsqueda RENIEC.\r\nCP002:" +
                " Creación de cliente con RUC 10 - Persona Natural con búsqueda SUNAT.\r\nCP003: Cr" +
                "eación de cliente con RUC 20 - Persona Jurídica con búsqueda SUNAT.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "CreacionCliente.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
 await testRunner.GivenAsync("el usuario ingresa al ambiente \'https://sigesdev.newfrontdev-qa.sigesonline.com/a" +
                    "uth/login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("el usuario inicia sesión con usuario \'pamela.tone@recsa.com\' y contraseña \'calida" +
                    "d\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.AndAsync("el usuario accede al módulo \'Ventas\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("el usuario accede al submodulo \'Nueva Venta\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creación de cliente con DNI - <Caso>")]
        [NUnit.Framework.CategoryAttribute("CreacionCliente")]
        [NUnit.Framework.CategoryAttribute("ClienteDNI")]
        [NUnit.Framework.TestCaseAttribute("CP001", "DOC. NACIONAL DE IDENTIDAD", "46326331", "MASCULINO", "Casado(a)", "caterno99@gmail.com", "927027827", "Brisas del huallaga comite 7 mz y lt 17, tingo maria", null)]
        public async System.Threading.Tasks.Task CreacionDeClienteConDNI_Caso(string caso, string tipoDocumento, string numeroDocumento, string genero, string estadoCivil, string correo, string telefono, string direccion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreacionCliente",
                    "ClienteDNI"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("TipoDocumento", tipoDocumento);
            argumentsOfScenario.Add("NumeroDocumento", numeroDocumento);
            argumentsOfScenario.Add("Genero", genero);
            argumentsOfScenario.Add("EstadoCivil", estadoCivil);
            argumentsOfScenario.Add("Correo", correo);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("Direccion", direccion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creación de cliente con DNI - <Caso>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 15
 await testRunner.WhenAsync("abre el modal de creación de cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.AndAsync(string.Format("selecciona tipo de documento \'{0}\' con número \'{1}\'", tipoDocumento, numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("completa datos generales con género \'{0}\', estado civil \'{1}\', correo \'{2}\' y tel" +
                            "éfono \'{3}\'", genero, estadoCivil, correo, telefono), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync(string.Format("ingresa dirección \'{0}\'", direccion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("guarda y confirma el cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.ThenAsync(string.Format("el cliente \'{0}\' queda registrado en la venta", numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creación de cliente con RUC 10 - Persona Natural - <Caso>")]
        [NUnit.Framework.CategoryAttribute("CreacionCliente")]
        [NUnit.Framework.CategoryAttribute("ClienteRUC10")]
        [NUnit.Framework.TestCaseAttribute("CP002", "REG. UNICO DE CONTRIBUYENTES", "10273622786", "MASCULINO", "Casado(a)", "caterno99@gmail.com", "927027827", "Brisas del huallaga comite 7 mz y lt 17, tingo maria", null)]
        public async System.Threading.Tasks.Task CreacionDeClienteConRUC10_PersonaNatural_Caso(string caso, string tipoDocumento, string numeroDocumento, string genero, string estadoCivil, string correo, string telefono, string direccion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreacionCliente",
                    "ClienteRUC10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("TipoDocumento", tipoDocumento);
            argumentsOfScenario.Add("NumeroDocumento", numeroDocumento);
            argumentsOfScenario.Add("Genero", genero);
            argumentsOfScenario.Add("EstadoCivil", estadoCivil);
            argumentsOfScenario.Add("Correo", correo);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("Direccion", direccion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creación de cliente con RUC 10 - Persona Natural - <Caso>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 29
 await testRunner.WhenAsync("abre el modal de creación de cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.AndAsync(string.Format("selecciona tipo de documento \'{0}\' con número \'{1}\'", tipoDocumento, numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync(string.Format("completa datos generales con género \'{0}\', estado civil \'{1}\', correo \'{2}\' y tel" +
                            "éfono \'{3}\'", genero, estadoCivil, correo, telefono), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync(string.Format("ingresa dirección \'{0}\'", direccion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("guarda y confirma el cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.ThenAsync(string.Format("el cliente \'{0}\' queda registrado en la venta", numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creación de cliente con RUC 20 - Persona Jurídica - <Caso>")]
        [NUnit.Framework.CategoryAttribute("CreacionCliente")]
        [NUnit.Framework.CategoryAttribute("ClienteRUC20")]
        [NUnit.Framework.TestCaseAttribute("CP003", "REG. UNICO DE CONTRIBUYENTES", "20270286675", "caterno99@gmail.com", "927027827", "Brisas del huallaga comite 7 mz y lt 17, tingo maria", null)]
        public async System.Threading.Tasks.Task CreacionDeClienteConRUC20_PersonaJuridica_Caso(string caso, string tipoDocumento, string numeroDocumento, string correo, string telefono, string direccion, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CreacionCliente",
                    "ClienteRUC20"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("TipoDocumento", tipoDocumento);
            argumentsOfScenario.Add("NumeroDocumento", numeroDocumento);
            argumentsOfScenario.Add("Correo", correo);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("Direccion", direccion);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Creación de cliente con RUC 20 - Persona Jurídica - <Caso>", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 43
 await testRunner.WhenAsync("abre el modal de creación de cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
 await testRunner.AndAsync(string.Format("selecciona tipo de documento \'{0}\' con número \'{1}\'", tipoDocumento, numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.AndAsync(string.Format("completa datos de empresa con correo \'{0}\' y teléfono \'{1}\'", correo, telefono), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync(string.Format("ingresa dirección \'{0}\'", direccion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("guarda y confirma el cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.ThenAsync(string.Format("el cliente \'{0}\' queda registrado en la venta", numeroDocumento), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
