// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Pedido
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("VerPedidos")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("Pedido")]
    public partial class VerPedidosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Pedido"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Pedido", "VerPedidos", "Como usuario del sistema\r\nQuiero registrar pedidos\r\nPara gestionar pedidos de cli" +
                "entes", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "VerPedidos.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
 await testRunner.GivenAsync("el usuario ingresa al ambiente \'https://sigesdev.newfrontdev-qa.sigesonline.com/a" +
                    "uth/login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.WhenAsync("el usuario inicia sesión con usuario \'pamela.tone@recsa.com\' y contraseña \'calida" +
                    "d\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
 await testRunner.AndAsync("el usuario accede al módulo \'Pedidos\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.AndAsync("el usuario accede al submodulo \'Ver Pedidos\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de nuevo pedido - Casos variados")]
        [NUnit.Framework.CategoryAttribute("RegistrarPedido")]
        [NUnit.Framework.TestCaseAttribute("1", "Gaseosa", "7753234003320", "10", "false", "false", "false", "NA", "NA", "0", "00000000", "inmediata", "el pedido se guardo correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "ninguno", "ninguno", "0", "false", "false", "false", "NA", "NA", "0", "75971755", "diferida", "Ningún producto seleccionado", null)]
        [NUnit.Framework.TestCaseAttribute("3", "Gaseosa", "7753234003313", "12", "true", "true", "true", "item", "$", "1", "00000000", "inmediata", "el pedido se guardo correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("4", "Azúcar", "7751234001115", "20", "false", "false", "true", "global", "%", "10", "20542245671", "diferida", "el pedido se guardo correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("5", "Gaseosa", "7753234003313", "5000", "false", "false", "false", "NA", "NA", "0", "75971755", "inmediata", "La cantidad debe ser menor o igual al stock", null)]
        public async System.Threading.Tasks.Task RegistroDeNuevoPedido_CasosVariados(string caso, string familia, string concepto, string cantidad, string igv, string det_Unif, string descuento, string tipo_Descuento, string modo_Descuento, string valor_Descuento, string cliente, string tipo_Entrega, string resultado_Esperado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarPedido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("familia", familia);
            argumentsOfScenario.Add("concepto", concepto);
            argumentsOfScenario.Add("cantidad", cantidad);
            argumentsOfScenario.Add("igv", igv);
            argumentsOfScenario.Add("det_unif", det_Unif);
            argumentsOfScenario.Add("descuento", descuento);
            argumentsOfScenario.Add("tipo_descuento", tipo_Descuento);
            argumentsOfScenario.Add("modo_descuento", modo_Descuento);
            argumentsOfScenario.Add("valor_descuento", valor_Descuento);
            argumentsOfScenario.Add("cliente", cliente);
            argumentsOfScenario.Add("tipo_entrega", tipo_Entrega);
            argumentsOfScenario.Add("resultado_esperado", resultado_Esperado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de nuevo pedido - Casos variados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 19
 await testRunner.AndAsync("el usuario selecciona la opción \'Nuevo Pedido\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.WhenAsync(string.Format("el usuario selecciona la familia \'{0}\'", familia), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
 await testRunner.AndAsync(string.Format("el usuario selecciona el concepto \'{0}\'", concepto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync(string.Format("el usuario ingresa la cantidad \'{0}\'", cantidad), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync(string.Format("el usuario activa IGV \'{0}\'", igv), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync(string.Format("el usuario activa DET.UNIF \'{0}\'", det_Unif), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.AndAsync(string.Format("el usuario configura descuento \'{0}\' \'{1}\' \'{2}\' \'{3}\'", descuento, tipo_Descuento, modo_Descuento, valor_Descuento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("el usuario abre la sección \'Facturación\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync(string.Format("el usuario busca el cliente \'{0}\'", cliente), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.AndAsync("el usuario abre la sección \'Entrega\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync(string.Format("el usuario selecciona tipo de entrega \'{0}\'", tipo_Entrega), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.AndAsync("el usuario registra el pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
 await testRunner.ThenAsync(string.Format("el sistema valida \'{0}\'", resultado_Esperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Invalidar pedido - Casos variados")]
        [NUnit.Framework.CategoryAttribute("InvalidarPedido")]
        [NUnit.Framework.TestCaseAttribute("1", "Producto agotado", "SI", "el pedido se Invalido correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "ninguno", "SI", "Boton SI deshabilitado", null)]
        public async System.Threading.Tasks.Task InvalidarPedido_CasosVariados(string caso, string motivo, string accion, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InvalidarPedido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("motivo", motivo);
            argumentsOfScenario.Add("accion", accion);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalidar pedido - Casos variados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 63
 await testRunner.GivenAsync("existe un pedido en estado registrado para invalidar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
 await testRunner.WhenAsync("el usuario selecciona la opción \'Invalidar pedido\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
 await testRunner.AndAsync(string.Format("el usuario ingresa el motivo \'{0}\'", motivo), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
 await testRunner.AndAsync(string.Format("el usuario confirma \'{0}\'", accion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
 await testRunner.ThenAsync(string.Format("el sistema valida \'{0}\'", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Confirmar pedido - Casos variados")]
        [NUnit.Framework.CategoryAttribute("ConfirmarPedido")]
        [NUnit.Framework.TestCaseAttribute("1", "false", "factura electronica", "F002", "20542245671", "inmediata", "true", "true", "Pedido confirmado correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "false", "factura electronica", "F002", "75971755", "inmediata", "false", "true", "Para emitir Factura Electrónica, el cliente debe tener RUC (11 dígitos)", null)]
        [NUnit.Framework.TestCaseAttribute("3", "false", "factura electronica", "ninguno", "20542245671", "diferida", "false", "true", "Ingrese el numero de serie", null)]
        [NUnit.Framework.TestCaseAttribute("4", "false", "factura electronica", "F002", "20542245671", "inmediata", "false", "false", "Monto insuficiente", null)]
        [NUnit.Framework.TestCaseAttribute("5", "true", "boleta de venta electronica", "B002", "75971635", "diferida", "false", "true", "Pedido confirmado correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("6", "false", "boleta de venta electronica", "B002", "00000000", "inmediata", "false", "true", "Pedido confirmado correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("7", "true", "boleta de venta electronica", "B002", "00000000", "inmediata", "false", "true", "Es necesario identificar al cliente, el total es mayor a S/.700", null)]
        [NUnit.Framework.TestCaseAttribute("8", "false", "nota de venta", "NV02", "75971755", "diferida", "false", "true", "Pedido confirmado correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("9", "false", "nota de venta", "NV02", "20602945589", "inmediata", "false", "true", "Pedido confirmado correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("10", "false", "nota de venta", "NV02", "20602945589", "inmediata", "false", "false", "Monto insuficiente", null)]
        [NUnit.Framework.TestCaseAttribute("11", "false", "boleta de venta electronica", "B002", "00000000", "inmediata", "true", "true", "Para guia de remision Necesita identificar al cliente con RUC o DNI", null)]
        public async System.Threading.Tasks.Task ConfirmarPedido_CasosVariados(string caso, string total_Mayor_700, string tipo_Comprobante, string serie, string cliente, string tipo_Entrega, string guia_Remision, string monto_Cubre_Total, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ConfirmarPedido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("total_mayor_700", total_Mayor_700);
            argumentsOfScenario.Add("tipo_comprobante", tipo_Comprobante);
            argumentsOfScenario.Add("serie", serie);
            argumentsOfScenario.Add("cliente", cliente);
            argumentsOfScenario.Add("tipo_entrega", tipo_Entrega);
            argumentsOfScenario.Add("guia_remision", guia_Remision);
            argumentsOfScenario.Add("monto_cubre_total", monto_Cubre_Total);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Confirmar pedido - Casos variados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 78
 await testRunner.GivenAsync(string.Format("existe un pedido base registrado para confirmar con total mayor a 700 \'{0}\'", total_Mayor_700), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
 await testRunner.WhenAsync("el usuario selecciona la opción \'Confirmar pedido\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
 await testRunner.AndAsync(string.Format("el usuario configura la facturacion \'{0}\' \'{1}\' \'{2}\'", tipo_Comprobante, serie, cliente), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
 await testRunner.AndAsync(string.Format("el usuario configura la entrega \'{0}\' \'{1}\'", tipo_Entrega, guia_Remision), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
 await testRunner.AndAsync(string.Format("el usuario configura el pago \'efectivo\' \'{0}\'", monto_Cubre_Total), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
 await testRunner.AndAsync("el usuario confirma el pedido preparado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
 await testRunner.ThenAsync(string.Format("el sistema valida \'{0}\'", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
