// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SIGES3_0.Features.Ventas
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Reportes")]
    public partial class ReportesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Ventas", "Reportes", "  Como usuario administrador\r\n  Quiero acceder al menu de Reportes de Ventas\r\n  P" +
                "ara validar la funcionalidad de generacion de reportes por Comprobantes y Concep" +
                "tos", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Reportes.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
    await testRunner.GivenAsync("el usuario ingresa al ambiente \'https://sigesdev.newfrontdev-qa.sigesonline.com/a" +
                    "uth/login\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("el usuario inicia sesión con usuario \'pamela.tone@recsa.com\' y contraseña \'calida" +
                    "d\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario accede al módulo \'Ventas\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("el usuario accede al submodulo \'Reportes\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar filtro de fechas en reporte de ventas")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("FiltroFechas")]
        [NUnit.Framework.TestCaseAttribute("CP0000", "BOLETA DE VENTA ELECTRONICA", "B002", "10/03/2026 12:00 am", "09/03/2026 11:59 pm", "No permite aplicar el filtro Inhabilitado", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "FACTURA ELECTRONICA", "F002", "09/03/2026 12:00 am", "23/03/2026 11:59 pm", "Aplica el filtro correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "NOTA DE VENTA(INTERNA)", "NV02", "01/03/2026 11:00 pm", "01/03/2026 12:59 pm", "Aplica el filtro correctamente", null)]
        public async System.Threading.Tasks.Task ValidarFiltroDeFechasEnReporteDeVentas(string caso, string tipoComprobante, string serie, string fechaHoraInicial, string fechaHoraFinal, string resultadoEsperado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "FiltroFechas"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("TipoComprobante", tipoComprobante);
            argumentsOfScenario.Add("Serie", serie);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            argumentsOfScenario.Add("resultadoEsperado", resultadoEsperado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar filtro de fechas en reporte de ventas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 15
 await testRunner.WhenAsync("selecciona la vista \"Comprobantes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Inicial\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Final\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync(string.Format("selecciona el tipo de comprobante \"{0}\"", tipoComprobante), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync(string.Format("selecciona la serie \"{0}\"", serie), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Comprobante\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.ThenAsync(string.Format("el sistema muestra el resultado esperado del reporte \"{0}\"", resultadoEsperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por comprobante")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorComprobante")]
        [NUnit.Framework.TestCaseAttribute("CP0000", "BOLETA DE VENTA ELECTRONICA", "B002", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "FACTURA ELECTRONICA", "F002", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "NOTA DE VENTA(INTERNA)", "NV02", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "NOTA DE CREDITO", "B002", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "NOTA DE DEBITO", "B002", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorComprobante(string caso, string tipoComprobante, string serie, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorComprobante"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("TipoComprobante", tipoComprobante);
            argumentsOfScenario.Add("Serie", serie);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por comprobante", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.WhenAsync("selecciona la vista \"Comprobantes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Inicial\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Final\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync(string.Format("selecciona el tipo de comprobante \"{0}\"", tipoComprobante), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync(string.Format("selecciona la serie \"{0}\"", serie), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Comprobante\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por serie")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorSerie")]
        [NUnit.Framework.TestCaseAttribute("CP0000", "03 : B002", "05/03/2026 12:00 am", "25/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorSerie(string caso, string comprobanteSerie, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorSerie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("ComprobanteSerie", comprobanteSerie);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por serie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.WhenAsync("selecciona la vista \"Series\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Inicial\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Final\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync(string.Format("selecciona el comprobante y serie \"{0}\"", comprobanteSerie), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Serie\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por conceptos (sin filtro adicional)")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorConceptos")]
        [NUnit.Framework.CategoryAttribute("Sinfiltro")]
        [NUnit.Framework.TestCaseAttribute("CP086", "CENTRO COMERCIAL CENTRAL", "Por Familia y Serie", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP087", "CENTRO COMERCIAL CENTRAL", "Por Categoría y Serie", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP088", "CENTRO COMERCIAL CENTRAL", "Según Horario", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP0000", "CENTRO COMERCIAL CENTRAL", "Por Comprobante con ICBPER", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorConceptosSinFiltroAdicional(string caso, string puntoVenta, string tarjeta, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorConceptos",
                    "Sinfiltro"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("PuntoVenta", puntoVenta);
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por conceptos (sin filtro adicional)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 68
    await testRunner.WhenAsync("selecciona la vista \"Conceptos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Inicial\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora \"{0}\" en el campo \"Fecha y Hora Final\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync(string.Format("selecciona el punto de venta \"{0}\"", puntoVenta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync(string.Format("hace clic en \"VER REPORTE\" en la tarjeta \"{0}\"", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por familia en la vista Conceptos")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorConceptos")]
        [NUnit.Framework.CategoryAttribute("PorFamilia")]
        [NUnit.Framework.TestCaseAttribute("CP070", "CENTRO COMERCIAL CENTRAL", "Gaseosa", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorFamiliaEnLaVistaConceptos(string caso, string puntoVenta, string familia, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorConceptos",
                    "PorFamilia"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("PuntoVenta", puntoVenta);
            argumentsOfScenario.Add("Familia", familia);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por familia en la vista Conceptos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 86
    await testRunner.WhenAsync("selecciona la vista \"Conceptos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.AndAsync(string.Format("selecciona el punto de venta \"{0}\"", puntoVenta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.AndAsync(string.Format("selecciona la familia \"{0}\"", familia), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Familia\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por característica en la vista Conceptos")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorConceptos")]
        [NUnit.Framework.CategoryAttribute("PorCaracteristica")]
        [NUnit.Framework.TestCaseAttribute("CP084", "CENTRO COMERCIAL CENTRAL", "MARCA", "POR CONCEPTO, CARACTERISTICAS Y FORMA DE PAGO", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP085", "CENTRO COMERCIAL CENTRAL", "TAMAÑO", "POR CARACTERISTICAS", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorCaracteristicaEnLaVistaConceptos(string caso, string puntoVenta, string caracteristica, string tarjeta, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorConceptos",
                    "PorCaracteristica"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("PuntoVenta", puntoVenta);
            argumentsOfScenario.Add("Caracteristica", caracteristica);
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por característica en la vista Conceptos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.WhenAsync("selecciona la vista \"Conceptos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
    await testRunner.AndAsync(string.Format("selecciona el punto de venta \"{0}\"", puntoVenta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.AndAsync(string.Format("selecciona la característica \"{0}\" en la tarjeta \"{1}\"", caracteristica, tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
    await testRunner.AndAsync(string.Format("hace clic en \"VER REPORTE\" en la tarjeta \"{0}\"", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por vendedor en la vista Vendedor")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorVendedor")]
        [NUnit.Framework.TestCaseAttribute("CP090", "FRANKLIN MARTINEZ HURTADO", "Gaseosa", "Inka Kola", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorVendedorEnLaVistaVendedor(string caso, string vendedor, string familia, string concepto, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorVendedor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Vendedor", vendedor);
            argumentsOfScenario.Add("Familia", familia);
            argumentsOfScenario.Add("Concepto", concepto);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por vendedor en la vista Vendedor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 117
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 118
    await testRunner.WhenAsync("selecciona la vista \"Vendedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.AndAsync(string.Format("selecciona el vendedor \"{0}\"", vendedor), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 122
    await testRunner.AndAsync(string.Format("selecciona \"{0}\" en el filtro \"Familias\" de la tarjeta \"Por Vendedor\"", familia), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
    await testRunner.AndAsync(string.Format("selecciona \"{0}\" en el filtro \"Conceptos\" de la tarjeta \"Por Vendedor\"", concepto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Vendedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por modalidad y concepto en la vista Vendedor")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorVendedor")]
        [NUnit.Framework.CategoryAttribute("PorModalidadConcepto")]
        [NUnit.Framework.TestCaseAttribute("CP091", "FRANKLIN MARTINEZ HURTADO", "VENTA NORMAL", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorModalidadYConceptoEnLaVistaVendedor(string caso, string vendedor, string modalidad, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorVendedor",
                    "PorModalidadConcepto"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Vendedor", vendedor);
            argumentsOfScenario.Add("Modalidad", modalidad);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por modalidad y concepto en la vista Vendedor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 134
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 135
    await testRunner.WhenAsync("selecciona la vista \"Vendedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
    await testRunner.AndAsync(string.Format("selecciona el vendedor \"{0}\"", vendedor), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.AndAsync(string.Format("selecciona \"{0}\" en el filtro \"Modalidad\" de la tarjeta \"Por Modalidad y Concepto" +
                            "\"", modalidad), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Modalidad y Concepto\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte por familia y vendedor en la vista Vendedor")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorVendedor")]
        [NUnit.Framework.CategoryAttribute("PorFamiliaVendedor")]
        [NUnit.Framework.TestCaseAttribute("CP092", "FRANKLIN MARTINEZ HURTADO", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReportePorFamiliaYVendedorEnLaVistaVendedor(string caso, string vendedor, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorVendedor",
                    "PorFamiliaVendedor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Vendedor", vendedor);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte por familia y vendedor en la vista Vendedor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 150
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 151
    await testRunner.WhenAsync("selecciona la vista \"Vendedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 152
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
    await testRunner.AndAsync(string.Format("selecciona el vendedor \"{0}\"", vendedor), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
    await testRunner.AndAsync("hace clic en \"VER REPORTE\" en la tarjeta \"Por Familia y Vendedor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte en la vista Grupos")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorGrupos")]
        [NUnit.Framework.TestCaseAttribute("CP093", "RECSA - CENTRAL", "CENTRO COMERCIAL CENTRAL", "Por Grupo", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP094", "RECSA - CENTRAL", "CENTRO COMERCIAL CENTRAL", "Por Familia y Grupo", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP095", "RECSA - CENTRAL", "CENTRO COMERCIAL CENTRAL", "Por Grupo Detallado", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReporteEnLaVistaGrupos(string caso, string establecimiento, string puntoVenta, string tarjeta, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorGrupos"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("Establecimiento", establecimiento);
            argumentsOfScenario.Add("PuntoVenta", puntoVenta);
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte en la vista Grupos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 164
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 165
    await testRunner.WhenAsync("selecciona la vista \"Grupos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
    await testRunner.AndAsync(string.Format("selecciona el establecimiento \"{0}\"", establecimiento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
    await testRunner.AndAsync(string.Format("selecciona el punto de venta \"{0}\"", puntoVenta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
    await testRunner.AndAsync(string.Format("hace clic en \"VER REPORTE\" en la tarjeta \"{0}\"", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("<Caso> Generar reporte en la vista Excepciones")]
        [NUnit.Framework.CategoryAttribute("Reportes")]
        [NUnit.Framework.CategoryAttribute("PorExcepciones")]
        [NUnit.Framework.TestCaseAttribute("CP096", "CENTRO COMERCIAL CENTRAL", "Por Notas de Credito", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP097", "CENTRO COMERCIAL CENTRAL", "Por Invalidaciones", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        [NUnit.Framework.TestCaseAttribute("CP098", "CENTRO COMERCIAL CENTRAL", "Por Notas de Debito", "05/03/2026 12:00 am", "05/03/2026 11:59 pm", null)]
        public async System.Threading.Tasks.Task CasoGenerarReporteEnLaVistaExcepciones(string caso, string puntoVenta, string tarjeta, string fechaHoraInicial, string fechaHoraFinal, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Reportes",
                    "PorExcepciones"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Caso", caso);
            argumentsOfScenario.Add("PuntoVenta", puntoVenta);
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            argumentsOfScenario.Add("fechaHoraInicial", fechaHoraInicial);
            argumentsOfScenario.Add("fechaHoraFinal", fechaHoraFinal);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("<Caso> Generar reporte en la vista Excepciones", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 181
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 182
    await testRunner.WhenAsync("selecciona la vista \"Excepciones\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 183
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora inicial \"{0}\"", fechaHoraInicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
    await testRunner.AndAsync(string.Format("el usuario ingresa la fecha y hora final \"{0}\"", fechaHoraFinal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
    await testRunner.AndAsync(string.Format("selecciona el punto de venta \"{0}\"", puntoVenta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 186
    await testRunner.AndAsync(string.Format("hace clic en \"VER REPORTE\" en la tarjeta \"{0}\"", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 187
    await testRunner.ThenAsync("el sistema genera el reporte exitosamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
