<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetSeleniumExtras.PageObjects" Version="3.11.0" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="ExtentReports" Version="5.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="2.2.1" />
    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Selenium.Support" Version="4.35.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.35.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drivers\" />
    <Folder Include="Features\FacturacionCiclica\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Category\EditCategory\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Category\DeleteCategory\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic Value\EditCharacteristicValue\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic Value\DeleteCharacteristicValue\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic Value\RegisterCharacteristicValue\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic\Common\EditCharacteristicCommon\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic\Common\RegisterCharacteristicCommon\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic\Distinctive\EditCharacteristicDistinctive\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Characteristic\Distinctive\RegisterCharacteristicDistinctive\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Family\DeleteFamily\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Presentation\EditPresentation\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Presentation\DeletePresentation\" />
    <Folder Include="Features\Items\TablesofDecision-Items\RegisterItemData\Presentation\RegisterPresentation\" />
    <Folder Include="Support\" />
    <Folder Include="TestResults\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\Adquisicion\NuevaAdquisicionNota.feature.cs">
      <DependentUpon>NuevaAdquisicionNota.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Adquisicion\NuevaAdquisiciónBoleta.feature.cs">
      <DependentUpon>NuevaAdquisiciónBoleta.feature</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
